services:
  # 1) API MOCK (json-server)
  - type: web
    name: d-journey-api
    runtime: node
    plan: free # <-- permitido aqui (web service Node)
    branch: main
    autoDeployTrigger: commit
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
    # Persistência (opcional e PAGA):
    # disk:
    #   name: data
    #   mountPath: /data
    #   sizeGB: 1
    # Se usar disco, ajuste o "start" no package.json para:
    # "start": "json-server --watch /data/db.json --host 0.0.0.0 --port $PORT --routes routes.json --delay 300"

  # 2) FRONT-END (Vite SPA)
  - type: web
    name: d-journey-web
    runtime: static # <-- Static Site usa runtime: static
    branch: main
    autoDeployTrigger: commit
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://d-journey-api.onrender.com # ajuste se o subdomínio da API for outro
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
